[tasks.format]
disabled = true

[tasks.test]
disabled = true

[tasks.pre-format]
disabled = true

[tasks.post-format]
disabled = true

[tasks.format-flow]
disabled = true

[tasks.pre-build]
disabled = true