[tasks.init]
disabled = true

#I tried with windows-alias here, but it didn't work.

[tasks.end]
script = [
    "xcopy c:\\Users\\Luciano\\RustProjects\\mem3_game\\mem3\\pkg\\*.* c:\\Users\\Luciano\\RustProjects\\mem3_game\\webfolder\\mem3\\pkg\\ /y ",
    "xcopy c:\\Users\\Luciano\\RustProjects\\mem3_game\\target\\debug\\mem3_server.exe c:\\Users\\Luciano\\RustProjects\\mem3_game\\webfolder\\ /y ",
# I cannot script the exact IP here.  
# It must be copied from the mem3_server.exe output.
    "start chrome http://127.0.0.22:80", 
    "start chrome http://127.0.0.22:80", 
    "cd webfolder",
    "mem3_server.exe"
]
